<?php
return [
    'data' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'classes' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null
    ],
    'action' => [
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'classes' => 'TableBuilderActions',
        'actions' => null
    ],
    'checkbox' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'classes' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'action' => null,
        'isEnabledCallback' => null
    ],
    'date' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'classes' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'format' => 'DD/MM/YYYY HH:mm:ss'
    ],
    'image' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'classes' => 'centercell',
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'width' => null,
        'tag' => 'em'
    ],
    'link' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'width' => null,
        'classes' => null,
        'shorten' => true,
        'maxlength' => 45,
        'target' => '_blank'
    ],
    'mail' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'width' => null,
        'classes' => null,
        'copycell' => true,
        'copytext' => '#tablebuilder::messages.clicktoselect#'
    ],
    'numeric' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'classes' => 'rightcell',
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'thousandsep' => "'",
        'currency' => '',
        'currencyposafter' => true,
        'decimalsep' => '.',
        'decimals' => 0
    ],
    'status' => [
        'sortable' => false,
        'title' => null,
        'completetitle' => null,
        'width' => null,
        'defaultOrder' => null,
        'customAsc' => null,
        'customDesc' => null,
        'classes' => 'centercell',
        'aIcons' => []
    ],
    'table' => [
        'searchable' => true,
        'rowcontextualtrigger' => 'trclass',
        'itemsperpage' => 20, // 0 for no pagination
        'pagechoices' => [
            10,
            20,
            30,
            50,
            100
        ],
        'encoding' => 'utf8',
        'additionalparams' => [],
        'paramsFunction' => null,
        'tableClass' => 'TableBuilder table table-condensed table-hover table-striped',
        'headersclass' => 'TableBuilderHeads',
        'searchdivclass' => 'TableBuilderSearch form-group',
        'searchinputgrpclass' => 'input-group',
        'searchresetbuttondivclass' => "input-group-append",
        'searchresetbuttonclass' => 'btn btn-outline-secondary',
        'eltspageclass' => 'TableBuilderEltsPage',
        'paginationclass' => 'TableBuilderPagination',
        'pagecontclass' => 'TableBuilderEltPageCont',
        'bottomclass' => 'TableBuilderBottom',
        'footerclass' => 'TableBuilderFooter',
        'buttonclass' => "btn btn-secondary",
        'ajaximgname' => 'far fa-hourglass',
        'uparrow' => 'fas fa-arrow-up',
        'downarrow' => 'fas fa-arrow-down',
        'leftarrow' => 'fas fa-angle-left fa-2x',
        'dblleftarrow' => 'fas fa-angle-double-left fa-2x',
        'rightarrow' => 'fas fa-angle-right fa-2x',
        'dblrightarrow' => 'fas fa-angle-double-right fa-2x',
        'buttondivarrow' => 'fas fa-level-up-alt fa-2x fa-flip-horizontal buttondivarrow',
        'ajaxerrormsg' => '#tablebuilder::messages.ajaxerrormsg#',
        'nodatastr' => '#tablebuilder::messages.nodatastr#',
        'chkheadlabel' => '#tablebuilder::messages.chkheadlabel#',
        'searchLabel' => '#tablebuilder::messages.searchLabel#',
        'searchresetlabel' => '#tablebuilder::messages.searchreset#',
        'eltLabel' => '#tablebuilder::messages.eltLabel#',
        'eltsParPageLabel' => '#tablebuilder::messages.eltsParPageLabel#',
        'buttons' => [],
        'eltsPerPageChngCallback' => null, // fnc eltsParPageChngCallback(iNbPages), pour admin, cookie etc.
        'aftertableload' => null
    ]
];
